name: build
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  publish:
    runs-on: [ "ubuntu-latest" ]
    steps:
      - uses: actions/checkout@v4
      - uses: coursier/cache-action@v6.4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker
      - name: build
        run: |-
          docker run -v ./:/app/ mulatinho/build-c:alpine make
      - name: test
        run: |-
          docker run -t -v ./:/app/ mulatinho/build-c:alpine make test
        env:
          TOKEN: ${{ secrets.PAT_DOCKER }}
