name: build
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  lint:
    runs-on: [ "ubuntu-latest" ]
    env:
      REPO_NAME: ${{ github.event.repository.name }}
    container:
      image: mulatinho/build-c:alpine
      volumes: 
        - /__w/${REPO_NAME}/${REPO_NAME}:/app

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: List contents
        run: ls -lah /app

      - name: build
        run: make lint
  build:
    runs-on: [ "ubuntu-latest" ]
    needs: [lint]
    env:
      REPO_NAME: ${{ github.event.repository.name }}
    container:
      image: mulatinho/build-c:alpine
      volumes: 
        - /__w/${REPO_NAME}/${REPO_NAME}:/app

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: List contents
        run: ls -lah /app

      - name: build
        run: make

      - name: test
        run: make test
